**1. Write a Python program to convert a list of numeric value into a one-dimensional
NumPy array.**


In [124]:
import numpy as np

lst=[12,13,100,36]
arr=np.array(lst)
print(arr)

[ 12  13 100  36]


**2. Create a 3x3 matrix with values ranging from 2 to 10.**

In [126]:
x = np.arange(2, 11).reshape(3, 3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


**3. Write a Python program to create a null vector of size 10 and update sixth value to 11.**

In [128]:
x=np.zeros(10)
print(x)
print("Update the 6th index to 11")
x[6]=11
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update the 6th index to 11
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


**4. Write a Python program to reverse an array (first element becomes last).**

In [130]:
x=np.array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37])
res = np.flip(x)
print(str(res))

[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


**5. Write a Python program to create a 2d array with 1 on the border and 0 inside.**

In [132]:
x = np.ones((5, 5))
print("Original array:")
print(x)
print("1 on the border and 0 inside in the array")
x[1:-1, 1:-1] = 0
print(x)

Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


**6. Write a Python program to add a border (filled with 0's) around an existing array.**

In [134]:
x = np.zeros((5, 5))
print("Original array:")
print(x)
print("0 on the border and 1 inside in the array")
x[1:-1, 1:-1] = 1
print(x)

Original array:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


**7. Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern..**

In [136]:
x = np.zeros((8, 8))
print("Original array:")
print(x)
print("New array:")
x[1::2,::2] = 1
x[::2, 1::2] = 1 
print(x)


Original array:
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
New array:
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


**8. Write a Python program to convert a list and tuple into arrays.**

In [138]:
list1 = [3, 4, 5, 6]
array1 = np.asarray(list1)
print("list into array")
print(array1)
tup1 = ([8,4,5],[1,2,3])
array2 =np.array(tup1)
print("Tupple into array")
print(array2)

list into array
[3 4 5 6]
Tupple into array
[[8 4 5]
 [1 2 3]]


**9. Write a Python program to append values to the end of an array.**

In [140]:
lst=[10, 20, 30]
print("original array")
print(lst)
lst=np.append(lst,[40])
lst=np.append(lst,[50])
lst=np.append(lst,[60])
lst=np.append(lst,[70])
lst=np.append(lst,[80])
lst=np.append(lst,[90])
print("new array")
print(lst)

original array
[10, 20, 30]
new array
[10 20 30 40 50 60 70 80 90]


**10. Write a Python program to find the real and imaginary parts of an array of complex
numbers.**

In [142]:
import numpy as np
complex_array = np.array([1.00000000 + 0.j, 0.70710678 + 0.70710678j])
real_part = np.real(complex_array)
imaginary_part = np.imag(complex_array)
print("Original array:", complex_array)
print("Real part of the array:")
print(real_part)
print("Imaginary part of the array:")
print(imaginary_part)


Original array: [1.   +0.j    0.707+0.707j]
Real part of the array:
[1.    0.707]
Imaginary part of the array:
[0.    0.707]


**11. Write a Python program to find the number of elements of an array, length of one
array element in bytes and total bytes consumed by the elements.**

In [144]:
x = np.array([1, 2, 3], dtype=np.float64)
print("Size of the array: ", x.size)
print("Length of one array element in bytes: ", x.itemsize)
print("Total bytes consumed by the elements of the array: ", x.nbytes)

Size of the array:  3
Length of one array element in bytes:  8
Total bytes consumed by the elements of the array:  24


**12. Write a Python program to find common values between two arrays.**

In [146]:
Array1 =[ 0, 10, 20, 40, 60]
Array2 =[10, 30, 40]
Array3=np.intersect1d(Array1,Array2)
print(Array3)

[10 40]


**13. Write a Python program to find the set difference of two arrays. The set difference will return the sorted, unique values in array1 that are not in array2.**

In [148]:
import numpy as np
Array1 =[ 0, 10, 20, 40, 60]
Array2 =[10, 30, 40]
Array3=np.setdiff1d(Array1,Array2)
print(Array3)

[ 0 20 60]


**14. Write a Python program to find the set exclusive-or of two arrays. Set exclusive-or will return the sorted, unique values that are in only one (not both) of the input arrays.**

In [150]:
Array1 =[ 0, 10, 20, 40, 60]
Array2 =[10, 30, 40]
Array3=np.setxor1d(Array1,Array2)
print(Array3)

[ 0 20 30 60]


**15(a). Write a Python program compare two arrays using numpy.**

In [152]:
a = np.array([1,2])
b = np.array([4,5])
 
print("Array a: ", a)
print("Array b: ", b)
 
print("a > b")
print(np.greater(a, b))
 
print("a >= b")
print(np.greater_equal(a, b))
 
print("a < b")
print(np.less(a, b))
 
print("a <= b")
print(np.less_equal(a, b))

Array a:  [1 2]
Array b:  [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True  True]
a <= b
[ True  True]


**15(b). Write a Python program to save a NumPy array to a text file.**

In [154]:
List = [1, 2, 3, 4, 5]
Array = np.array(List)
print('Array:\n', Array)
file = open("file1.txt", "w+")
content = str(Array)
file.write(content)
file.close()
file = open("file1.txt", "r")
content = file.read() 
print("\nContent in file1.txt:\n", content)
file.close()

Array:
 [1 2 3 4 5]

Content in file1.txt:
 [1 2 3 4 5]


**16. Write a Python program to create a contiguous flattened array.**

In [156]:
import numpy as np
original_array = np.array([[10, 20, 30], [20, 40, 50]])
flattened_array = original_array.ravel()
print("Original array:")
print(original_array)
print("New flattened array:")
print(flattened_array)


Original array:
[[10 20 30]
 [20 40 50]]
New flattened array:
[10 20 30 20 40 50]


**17. Write a Python program to create a contiguous flattened array.**

In [158]:
arr = np.array([10, 20, 30, 40, 50])
print(arr)
print(arr.dtype)
arr = arr.astype('float64') 
print(arr) 
print(arr.dtype)

[10 20 30 40 50]
int32
[10. 20. 30. 40. 50.]
float64


**18. Write a Python program to create a 3-D array with ones on a diagonal and zeros
elsewhere.**

In [160]:
shape = (3, 3, 3) 
array_3d = np.zeros(shape, dtype=int)
for i in range(min(shape)):
    array_3d[i, i, i] = 1
print("3D Array with ones on the diagonal:")
print(array_3d)


3D Array with ones on the diagonal:
[[[1 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 1 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 1]]]


**19. Write a Python program to create an array which looks like below array.**

In [162]:
array = np.zeros((4, 3), dtype=int)
array[1:, :] = np.tril(np.ones((3, 3), dtype=int), k=0)
print(array)

[[0 0 0]
 [1 0 0]
 [1 1 0]
 [1 1 1]]


**20. Write a Python program to concatenate two 2-dimensional arrays.**

In [164]:
arr1 = np.arange(1, 10).reshape(3, 3)
arr2 = np.arange(10, 19).reshape(3, 3)
np.stack((arr1, arr2), axis=1)

array([[[ 1,  2,  3],
        [10, 11, 12]],

       [[ 4,  5,  6],
        [13, 14, 15]],

       [[ 7,  8,  9],
        [16, 17, 18]]])

**21. Write a Python program to make an array immutable (read-only).**

In [166]:
a = np.zeros(11)
print("Before any change ")
print(a)
 
a[1] = 2
print("Before after first change ")
print(a)
 
a.setflags(write=False)
print("After making array immutable on attempting  second change ")
a[1] = 7

Before any change 
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Before after first change 
[0. 2. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
After making array immutable on attempting  second change 


ValueError: assignment destination is read-only

**22. Write a Python program to create an array of (3, 4) shape, multiply every element
value by 3 and display the new array.**

In [177]:
x = np.arange(0, 12).reshape(3, 4)
print("original array:")
print(x)
print("new array:")
x = x * 3 
print(x)


original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
new array:
[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


**23. Write a Python program to convert a NumPy array into Python list structure.**

In [175]:
arr = np.array([[0,1],[2,3],[4,5]]) 
print(arr)
arr = arr.tolist()
print("Array to list: ")
print(arr)

[[0 1]
 [2 3]
 [4 5]]
Array to list: 
[[0, 1], [2, 3], [4, 5]]


**24. Write a Python program to convert a NumPy array into Python list structure.**

In [173]:
import numpy as np
arr = np.array([0.26153123, 0.52760141, 0.5718299, 0.5927067, 0.7831874,
                0.69746349, 0.35399976, 0.99469633, 0.0694458, 0.54711478])
print("Original array elements (NumPy Array):")
print(arr)
arr_list = arr.tolist()
rounded_arr = np.round(arr, 3)
print("\nAfter conversion (Python List):")
print(rounded_arr)

Original array elements (NumPy Array):
[0.262 0.528 0.572 0.593 0.783 0.697 0.354 0.995 0.069 0.547]

After conversion (Python List):
[0.262 0.528 0.572 0.593 0.783 0.697 0.354 0.995 0.069 0.547]


**25. Write a Python program to suppresses the use of scientific notation for small
numbers in numpy array.**

In [171]:

arr = np.array([1.6e-10, 1.6, 1.2e3, 2.35e-1])
print("Original array elements:")
print(arr)
np.set_printoptions(suppress=True, precision=3)
print("\nPrint array values with precision 3:")
print(arr)


Original array elements:
[   0.       1.6   1200.       0.235]

Print array values with precision 3:
[   0.       1.6   1200.       0.235]


**26. Write a Python program to how to add an extra column to an numpy array.**

In [169]:

ini_array = np.array([[10, 20, 30], [40, 50, 60]])
print("initial_array : ", str(ini_array));
column_to_be_added = np.array([[100], [200]])
arr = np.append(ini_array, column_to_be_added, axis=1)
print ("resultant array", str(arr))

initial_array :  [[10 20 30]
 [40 50 60]]
resultant array [[ 10  20  30 100]
 [ 40  50  60 200]]


**27. Write a Python program to remove specific elements in a numpy array.**

In [167]:

a = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print("Original array:")
print(a)
indices_to_remove = [0, 3, 4]
a = np.delete(a, indices_to_remove)
print("\nArray after deleting first, fourth, and fifth elements:")
print(a)


Original array:
[ 10  20  30  40  50  60  70  80  90 100]

Array after deleting first, fourth, and fifth elements:
[ 20  30  60  70  80  90 100]
